module.exports = {
  collectCoverageFrom: [
    "**/*.{js,jsx,ts,tsx}",
    "!**/*.d.ts",
    "!**/*.skeleton.tsx",
    "!**/node_modules/**",
    "!**/__mocks__/**",
    "!**/.next/**",
    "!**/coverage/**",
    "!**/jest.config.js/**",
    "!**/next.config.js/**",
    "!**/postcss.config.js/**",
    "!**/tailwind.config.js/**",
    "!**/types*/**",
    "!**/lib*/**",
    "!**/model*/**",
    "!**/middleware.ts**",
    "!**/mocks*/**",
  ],
  moduleNameMapper: {
    "^.+\\.module\\.(css|sass|scss)$": "identity-obj-proxy",
    "^.+\\.(css|sass|scss)$": "<rootDir>/__mocks__/styleMock.js",
    "^.+\\.(png|jpg|jpeg|gif|webp|avif|ico|bmp|svg)$": `<rootDir>/__mocks__/fileMock.js`,
    "^@/components/(.*)$": "<rootDir>/components/$1",
    "^@/pages/(.*)$": "<rootDir>/pages/$1",
    "^@/modules/(.*)$": "<rootDir>/modules/$1",
    "^@/services/(.*)$": "<rootDir>/services/$1",
    "^@/utils/(.*)$": "<rootDir>/utils/$1",
    "^@/types/(.*)$": "<rootDir>/types/$1",
    "^@/mocks/(.*)$": "<rootDir>/mocks/$1",
    "^@/hooks/(.*)$": "<rootDir>/hooks/$1",
  },
  setupFiles: ["<rootDir>/test.env.ts"],
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  testPathIgnorePatterns: ["<rootDir>/node_modules/", "<rootDir>/.next/"],
  transform: {
    "^.+\\.(js|jsx|ts|tsx)$": ["babel-jest", { presets: ["next/babel"] }],
  },
  transformIgnorePatterns: [
    "/node_modules/",
    "^.+\\.module\\.(css|sass|scss)$",
  ],
  testEnvironment: "jest-environment-jsdom",
};
