export enum AppRoutes {
  Default = "/",
  Home = "/home",
  MovieDetails = "/home/[movieId]",
  Movies = "/movies",
  MovieByGenreDetails = "/movies/[movieByGenreId]",
  Serials = "/serials",
  SerialDetails = "/serials/[serialId]",
  SignIn = "/auth/sign-in",
  SignUp = "/auth/sign-up",
  Profile = "/profile",
  SearchMovies = "/search/movie",
  SearchMoviesDetails = "/search/movie/[movieSearchParam]",
  SearchSerials = "/search/tv",
  SearchSerialsDetails = "/search/tv/[tvSerialSearchParam]",
}

export enum RequestMethod {
  GET = "GET",
  POST = "POST",
  DELETE = "DELETE",
  PUT = "PUT",
  PATCH = "PATCH",
}

export enum QueryString {
  serials = "serials",
  serialDetails = "serialDetails",
  moviesByGenre = "moviesByGenre",
  moviesByGenreDetails = "movieByGenreDetails",
  moviesForHomePage = "moviesForHomePage",
  moviesForHomePageDetails = "moviesForHomePageDetails",
  moviesForSearchPage = "moviesForSearchPage",
  tvSerialsForSearchPage = "tvSerialsForSearchPage",
  favoritesMoviesOrSerials = "favoritesMoviesOrSerials",
  movieOrSerialRating = "movieOrSerialRating",
  updateProfileData = "updateProfileData",
}

export enum SliderTitle {
  Default = "",
  PopularMoviesOrSerials = "Popular",
  TopRatedMoviesOrSerials = "Top Rated",
  LatestMoviesOrSerials = "Latest",
  NowPlayingMovies = "Now Playing",
  TrendingMovies = "Trending",
  UpcomingMovies = "Upcoming",
  ActionMovies = "Action",
  ComedyMovies = "Comedy",
  HorrorMovies = "Horror",
  ThrillerMovies = "Thriller",
  HistoryMovies = "History",
  Documentaries = "Documentaries",
  WarMovies = "War",
  WesternMovies = "Western",
  SerialsAiringToday = "Airing Today",
  SerialsOnAir = "On The Air",
  MyList = "My List",
}

export enum SeeMorePageRoutes {
  NowPlaying = "/home/now-playing",
  Popular = "/home/popular",
  TopRated = "/home/top-rated",
  Trending = "/home/trending",
  Upcoming = "/home/upcoming",
  ActionMovies = "/movies/action",
  ComedyMovies = "/movies/comedy",
  HorrorMovies = "/movies/horror",
  ThrillerMovies = "/movies/thriller",
  HistoryMovies = "/movies/history",
  Documentaries = "/movies/documentaries",
  WarMovies = "/movies/war",
  WesternMovies = "/movies/western",
  PopularSerials = "/serials/popular",
  TopRatedSerials = "/serials/top-rated",
  SerialsAiringToday = "/serials/airing-today",
  SerialsOnAir = "/serials/on-air",
  FavoritesHomePage = "/home/favorites",
  FavoritesMoviesPage = "/movies/favorites",
  FavoritesSerialsPage = "/serials/favorites",
}

export enum SeeMorePageQueryString {
  PopularMovies = "Popular Movies",
  TopRatedMovies = "Top Rated Movies",
  NowPlayingMovies = "Now Playing",
  TrendingMovies = "Trending",
  UpcomingMovies = "Upcoming",
  ActionMovies = "Action",
  ComedyMovies = "Comedy",
  HorrorMovies = "Horror",
  ThrillerMovies = "Thriller",
  HistoryMovies = "History",
  Documentaries = "Documentaries",
  WarMovies = "War",
  WesternMovies = "Western",
  SerialsAiringToday = "Airing Today",
  SerialsOnAir = "On The Air",
  PopularSerials = "Popular Serials",
  TopRatedSerials = "Top Rated Serials",
}
