export const DEFAULT_AVATAR_IMAGE_MEASUREMENT = "50";
export const DEFAULT_LOGO_IMAGE_MEASUREMENT = "70";

export const SCROLLED_AVATAR_IMAGE_MEASUREMENT = "40";
export const SCROLLED_LOGO_IMAGE_MEASUREMENT = "60";
