import { v4 as uuidv4 } from "uuid";

import { SeeMorePageRoutes, SliderTitle } from "@/types/enums";
import { AppPageData, PageSlider, SliderConfig } from "@/types/interfaces";

export const sliderConfig = <T extends AppPageData>({
  data,
  isHomePage,
  isMoviesPage,
  isSerialsPage,
  route,
  hasFavorites,
  favoritesSeeMoreRoute,
}: PageSlider<T>): SliderConfig[] => {
  const commonClassName = "mb-4";

  return [
    {
      id: uuidv4(),
      data: data?.favorites ?? [],
      title: SliderTitle.MyList,
      className: commonClassName,
      route,
      hasFavorites,
      favoritesSeeMoreRoute,
    },
    {
      id: uuidv4(),
      data: data?.actionMovies?.results ?? [],
      title: SliderTitle.ActionMovies,
      className: commonClassName,
      isMoviesPage,
      seeMoreRoute: SeeMorePageRoutes.ActionMovies,
      route,
    },
    {
      id: uuidv4(),
      data: data?.comedyMovies?.results ?? [],
      title: SliderTitle.ComedyMovies,
      className: commonClassName,
      isMoviesPage,
      seeMoreRoute: SeeMorePageRoutes.ComedyMovies,
      route,
    },
    {
      id: uuidv4(),
      data: data?.documentariesMovies?.results ?? [],
      title: SliderTitle.Documentaries,
      className: commonClassName,
      isMoviesPage,
      seeMoreRoute: SeeMorePageRoutes.Documentaries,
      route,
    },
    {
      id: uuidv4(),
      data: data?.historyMovies?.results ?? [],
      title: SliderTitle.HistoryMovies,
      className: commonClassName,
      isMoviesPage,
      seeMoreRoute: SeeMorePageRoutes.HistoryMovies,
      route,
    },
    {
      id: uuidv4(),
      data: data?.horrorMovies?.results ?? [],
      title: SliderTitle.HorrorMovies,
      className: commonClassName,
      isMoviesPage,
      seeMoreRoute: SeeMorePageRoutes.HorrorMovies,
      route,
    },
    {
      id: uuidv4(),
      data: data?.nowPlayingMovies?.results ?? [],
      title: SliderTitle.NowPlayingMovies,
      className: commonClassName,
      isHomePage,
      seeMoreRoute: SeeMorePageRoutes.NowPlaying,
      route,
    },
    {
      id: uuidv4(),
      data: data?.popularMovies?.results ?? [],
      title: SliderTitle.PopularMoviesOrSerials,
      className: commonClassName,
      isHomePage,
      seeMoreRoute: SeeMorePageRoutes.Popular,
      route,
    },
    {
      id: uuidv4(),
      data: data?.popularSerials?.results ?? [],
      title: SliderTitle.PopularMoviesOrSerials,
      className: commonClassName,
      isSerialsPage,
      seeMoreRoute: SeeMorePageRoutes.PopularSerials,
      route,
    },
    {
      id: uuidv4(),
      data: data?.serialsAiringToday?.results ?? [],
      title: SliderTitle.SerialsAiringToday,
      className: commonClassName,
      isSerialsPage,
      seeMoreRoute: SeeMorePageRoutes.SerialsAiringToday,
      route,
    },
    {
      id: uuidv4(),
      data: data?.serialsOnAir?.results ?? [],
      title: SliderTitle.SerialsOnAir,
      className: commonClassName,
      isSerialsPage,
      seeMoreRoute: SeeMorePageRoutes.SerialsOnAir,
      route,
    },
    {
      id: uuidv4(),
      data: data?.thrillerMovies?.results ?? [],
      title: SliderTitle.ThrillerMovies,
      className: commonClassName,
      isMoviesPage,
      seeMoreRoute: SeeMorePageRoutes.ThrillerMovies,
      route,
    },
    {
      id: uuidv4(),
      data: data?.topRatedMovies?.results ?? [],
      title: SliderTitle.TopRatedMoviesOrSerials,
      className: commonClassName,
      isHomePage,
      seeMoreRoute: SeeMorePageRoutes.TopRated,
      route,
    },
    {
      id: uuidv4(),
      data: data?.topRatedSerials?.results ?? [],
      title: SliderTitle.TopRatedMoviesOrSerials,
      className: commonClassName,
      isSerialsPage,
      seeMoreRoute: SeeMorePageRoutes.TopRatedSerials,
      route,
    },
    {
      id: uuidv4(),
      data: data?.trendingMovies?.results ?? [],
      title: SliderTitle.TrendingMovies,
      className: commonClassName,
      isHomePage,
      seeMoreRoute: SeeMorePageRoutes.Trending,
      route,
    },
    {
      id: uuidv4(),
      data: data?.upcomingMovies?.results ?? [],
      title: SliderTitle.UpcomingMovies,
      className: commonClassName,
      isHomePage,
      seeMoreRoute: SeeMorePageRoutes.Upcoming,
      route,
    },
    {
      id: uuidv4(),
      data: data?.warMovies?.results ?? [],
      title: SliderTitle.WarMovies,
      className: commonClassName,
      isMoviesPage,
      seeMoreRoute: SeeMorePageRoutes.WarMovies,
      route,
    },
    {
      id: uuidv4(),
      data: data?.westernMovies?.results ?? [],
      title: SliderTitle.WesternMovies,
      className: commonClassName,
      isMoviesPage,
      seeMoreRoute: SeeMorePageRoutes.WesternMovies,
      route,
    },
  ];
};
